packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - blake-hash
  - bufferutil
  - es5-ext
  - esbuild
  - keccak
  - lz4
  - protobufjs
  - secp256k1
  - utf-8-validate
