version: '3.8'

services:
  trpc-server:
    build: .
    image: chaingraph-trpc-server:latest
    ports:
      - '8080:80'
    environment:
      # Number of PM2 instances to run
      - INSTANCES=${INSTANCES:-4}

      # Base port for internal servers (PM2 will increment for each instance)
      - PORT=${PORT:-4021}

      # Database configuration
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres@host.docker.internal:5432/chaingraph}

      # Kafka configuration
      - KAFKA_BROKERS=${KAFKA_BROKERS:-host.docker.internal:9092}

      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - NODE_ENV=${NODE_ENV:-production}

    restart: unless-stopped

    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

    # Logging configuration
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'

    # Health check
    healthcheck:
      test: [CMD, wget, --no-verbose, --tries=1, --spider, 'http://localhost/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Networks (optional - for connecting with other services)
networks:
  default:
    name: chaingraph-network
    external: true
